export const data = [
    {
        id: '1',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '2',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '3',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '4',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '5',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '6',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '7',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '8',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '9',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '10',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '11',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '12',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '13',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '14',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '15',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '16',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '17',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '18',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '19',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '20',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '21',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '22',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '23',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '24',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Zed',
            username: 'Omeage',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
    {
        id: '25',
        type: 'custom',
        position: { x: 0, y: 0 },
        data: {
            profile: 'https://avatars.githubusercontent.com/u/10358415?v=4',
            name: 'Brian',
            username: 'KyawVer',
            desc: 'I hope my contribution will be truly helpful to those who are struggling to survive during the flooding crisis. I am very happy to donate my funds effectively to those in need, and I since...',
        },
    },
];
